#!/bin/bash

PORT="22"
INVENTORY=`mktemp`

trap 'myexit; exit' EXIT SIGINT SIGQUIT
myexit()
{
    #[ -e $INVENTORY ] && rm $INVENTORY
    true
}


ansible --version > /dev/null 2>&1
if [ "$?" != "0" ]; then
   echo "Please install ansible first"
   exit 1
fi

if [ -z "$1" ]; then
   echo "Usage: $0 <username@host>"
   exit 2
fi

[ -n "$2" ] && PORT="$2"

USER=`echo $1 | cut -d@ -f1`
HOST=`echo $1 | cut -d@ -f2`

echo "testhost ansible_ssh_user=$USER ansible_ssh_host=$HOST ansible_ssh_port=$PORT" > $INVENTORY
ansible-playbook -i $INVENTORY -k rea.yml
