#!/bin/bash

# Make sure temporary inventory file is removed before exit
trap 'myexit; exit' EXIT SIGINT SIGQUIT
myexit()
{
    [ -e $INVENTORY ] && rm $INVENTORY > /dev/null 2>&1
}

# Check if Ansible is installed
ansible --version > /dev/null 2>&1
[ "$?" != "0" ] && { echo "Please install ansible first"; exit 1; }

# Validate parameters
[ -z "$1" ] && { echo "Usage: $0 <username@host>" exit 2; }

# Parse username and hostname
if [[ "$1" == *"@"* ]]; then
    USER=`echo $1 | cut -d@ -f1`
    HOST=`echo $1 | cut -d@ -f2`
else
    echo "Invalid username/hostname: $1"
    exit 3
fi
[ -z "$USER" -o -z "$HOST" ] && { echo "Invalid user/hostname: $1"; exit 4; }
[ -n "$2" ] && PORT="$2" || PORT="22"

# Generate ansible inventory file
INVENTORY=`mktemp`
echo "testhost ansible_ssh_user=$USER ansible_ssh_host=$HOST ansible_ssh_port=$PORT" > $INVENTORY

# Configure the host
ansible-playbook -i $INVENTORY -k rea.yml
